
services:
  graphdb:
    image: ontotext/graphdb:10.7.3
    ports:
      - "7200:7200"
    volumes:
      - ./volumes-gitexclude/graphdb:/opt/graphdb/home
      - ./jdbc:/opt/graphdb/dist/lib/jdbc
    environment:
      - GRAPHDB_HOME=/opt/graphdb/home
      - JAVA_OPTS=-Xmx2g
    networks:
      - db_network
      
  dremio:
    image: dremio/dremio-oss
    user: root
    ports:
      - "9047:9047"
      - "31010:31010"
      - "32010:32010"
      - "45678:45678"
    volumes:
      - ./volumes-gitexclude/dremio/data:/opt/dremio/data
      - ./volumes-gitexclude/dremio/logs:/opt/dremio/logs
      - ./data/csv:/csv
      - ./jdbc:/jdbc
    networks:
      - db_network
    entrypoint: |
      /bin/bash -c "
      echo 'Copying driver'
      cp -n /opt/dremio/jars/jdbc-driver/*.jar /jdbc/driver-gitexclude.jar
      echo 'Starting dremio'
      cd /opt/dremio
      bin/dremio start-fg 
      " 

  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      # Example auth - just for testing purposes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: example
    volumes:
      - ./volumes-gitexclude/postgres:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - db_network


  pgadmin:
    image: dpage/pgadmin4:7.8 # Ensure this is the latest stable version or a specific version
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
