services:
  db:
    image: openjdk:8-jdk-alpine
    volumes:
      - ./h2:/opt/h2
    working_dir: '/opt/h2'
    command: [ "java", "-cp", "/opt/h2/bin/h2-1.4.196.jar", "org.h2.tools.Server", "-tcpAllowOthers", "-webAllowOthers" ]
    ports:
      - "8082:8082"
      - "9082:9082"
  ontop:
    image: ontop/ontop
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/university-complete.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/university-complete.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/university-complete.properties
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      ONTOP_LAZY_INIT: "true"
    volumes:
      - ./input:/opt/ontop/input
      - ./h2/bin:/opt/ontop/jdbc
    ports:
      - "8080:8080"